name: Generate favicon

on: 
  push:
    branches:
      - experimental
  schedule:
    - cron:  '0 0 * * *'

jobs:
  generateFavicon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate favicon
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub"
          npm install
          wget -O favicon.png https://avatars2.githubusercontent.com/u/18190639?s=460&v=4
          node favicon-gen.js
      - name: Push favicon
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Rebuild page
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node build.js sorp92 sorp92.github.io